language: php
php:
  - '5.6'
before_script:
  - wget https://phar.phpunit.de/phpunit-5.7.0.phar  
  - mv phpunit-5.7.0.phar phpunit.phar
script: php phpunit.phar _tests/_unit/_model/ModelTest.class.php